name: linting, testing, and deployment
on:
  push:
    branches: [master]
  puull_request:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
      run: npm install
      
      - name: run build
      run: npm run build-prod
      - name: run build
      run: npm run build-prod
      - name: run build
      run: npm run build-prod
      - name: run build
      run: npm run build-prod
      - name: run build
      run: npm run build-prod
      - name: run build
      run: npm run build-prod





